# Generated by Django 4.2.16 on 2024-11-04 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medication_sku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationsku',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='medicationsku',
            unique_together={('medication_name', 'presentation', 'dose', 'unit')},
        ),
    ]
